export { default as FrontPage } from './FrontPage'
export { default as MainPage } from './MainPage'
export { default as SettingPage } from './SettingPage'
export { default as ProfilePage } from './ProfilePage'
export { LearningPage, QuizPage, ReviewPage } from './main'
export { default as LogInPage } from './LogInPage'
export { SignUp, NameInput, AgeInput } from './signUp'
